### ISSUE TITLE
add option to retrieve shear values in different sign conventions

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#108]
The proposal is to add an option (something like `convention='treecorr'` or `convention='phosim'`) to the reader and the reader will return the shear (gamma) values using the specified convention. 

(cc @rmjarvis @cwwalter @danielsf @jchiang87 @katrinheitmann)

**Comment by rmjarvis** [comment]
Just copying over some of my thoughts on this from a Slack thread:

The "treecorr" convention defines g1,g2 relative to north being up, as seen from earth.  Which means RA increases to the left.  This is the convention used by: TreeCorr, GalSim, ngmix measurements, and all DES catalogs.  IMO (not surprisingly), this is the most sensible convention to use, and I'd favor this being the default value if the user doesn't specify something else.

The "phosim" convention defines g1,g2 relative to north being up and east being to the right.  This is kind of the naive choice if you don't think about it too hard, since RA increases to the east, so it's easy to just have that increasing to the right.  However, this is actually how the galaxy looks as seen from infinity looking back through space towards earth, which doesn't really make much sense.  This is currently the convention used by PhoSim and the DC2 (and presumably DC1) extragalactic catalogs.

**Comment by yymao** [comment]
Question on implementation detail: do people prefer to have a different property (e.g. `shear_2_phosim`), or a keyword argument supplied at catalog load time that changes the definition of `shear_2`?

**Comment by danielsf** [comment]
I agree with Jim: have a separate column makes it less likely that we will accidentally use the wrong thing.  It's still going to happen, but it will happen less frequently.

**Comment by yymao** [comment]
Now implemented in #111
