### ISSUE TITLE
coadd reader: native quantities with `slot_PsfFlux` and `ext_shapeHSM` are not per band.  Change to `base_PsfFlux` and explicitly use and document `base_SdssShape``? 

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#131]
In [Lines 145-147 of the coadd reader](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/dc2_coadd.py#L145), we have:
```python
    modifiers['psFlux_{}_lsst'.format(band)] = '{}_slot_PsfFlux_flux'.format(band)
    modifiers['psFlux_flag_{}_lsst'.format(band)] = '{}_slot_PsfFlux_flag'.format(band)
    modifiers['psFlux_err_{}_lsst'.format(band)] = '{}_slot_PsfFlux_fluxSigma'.format(band)
```

But looking at the native quantities, I only find:
``` python 
[
    ...
    'slot_PsfFlux_flag',
    'slot_PsfFlux_flux',
    'slot_PsfFlux_fluxSigma',
    ...
]
```
and 
```python
[
    ...
    'u_base_PsfFlux_flag',
    'u_base_PsfFlux_flux',
    'u_base_PsfFlux_fluxSigma',
    ...
]
```
So this is probably a typo?

**Comment by yymao** [comment]
Also, I think the derived quantity name should be `psf_flux_{}_lsst` etc.

**Comment by yymao** [comment]
Also need to update `SCHEMA.md` accordingly.

**Comment by wmwv** [comment]
The derived quantity names should be `psFlux` and `psFluxErr`, according to the DPDD[*].  Given that we're expanding the filter names, that means we should have

`psFlux_{}_lsst`
`psFluxErr_{}_lsst`

presently we have

`psFlux_{}_lsst`
`psFlux_err_{}_lsst`

I think we can leave flag as
`psFlux_flag_{}_lsst`

but we should change to `psFluxErr_{}_lsst`

[*] The names in the DPDD are actually `psFlux` and `psCov`, where `psFlux` and `psCov` are each described as a 6-element vector.  That doesn't really make sense for `psCov` [**].  The 6-element vector version is just the error.  So, in analogy with the DPDD colums of `apFlux` and `apFluxErr`, I suggest that we go with `psFluxErr` instead of `psCov`.

[**] The name `psCov` instead of `psFluxCov` also doesn't make sense.

**Comment by yymao** [comment]
Oh, ok, thanks! I wasn't aware that those names are from DPDD. Then I suggest that we label them in `SCHEMA.md` so that people can understand the different naming styles.

**Comment by wmwv** [comment]
The shape measurements we want to use, the HSM measurements, are only available in the merged detection reference catalog.  They are not currently re-computed per band in the forced photometry.  They should be in the future.

We do have base_sdssShape measurements per-band.  And these are what's being used for, e.g., `psf_fwhm_{}`.

**Comment by wmwv** [comment]
Correct.

**Comment by wmwv** [comment]
The title of this issues should be changed to:

**Comment by wmwv** [comment]
We did.  `Ixx`, `Iyy`, `Ixy` (no band) are the `ext_shapeHSM_HsmSourceMoments`.

**Comment by wmwv** [comment]
I'm editing `dc2_coadd.py` now to make this more explicit and will update the `SCHEMA.md` appropriately.
