### ISSUE TITLE
Create schema.yaml 'default' that causes an attribute lookup. (DC2 object reader)

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#210]
There are some descriptors of a given catalog that may be useful to express as columns.  E.g., tract and patch.  Potentially pixel_scale -- although for sanity that should always be fixed for a given run.
Consider creating a schema.yaml default value, 'attr', that does an attribute lookup to populate a column with metadata about the catalog stored as an attribute of the object table?

If we ever provide access to per-image catalogs, then this might be very useful.  One might want to build a collection of observations across different images, but each having the airmass, LST, date-obs, etc.

**Comment by wmwv** [comment]
Propose this is is implemented as a composite catalog with a join against a VisitInfo or similar observation metadata table.

**Comment by yymao** [comment]
I think this is no longer relevant for object catalogs since we have moved to using parquet format -- which is cheap to store a column with a constant value. In fact, `tract` and `patch` are now store in the parquet file as columns. 

For per-image catalogs or other uses (like transient catalogs), this is more of an issue of how to join different catalogs, which is a separated question that is quite different in nature. 

I'm closing this. If needed, please reopen or open a new issue.
