### ISSUE TITLE
Include cModel flux as GCR quantities in DPDD-like object catalogs

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/gcr-catalogs#254]
Right now we have the GCR quantity `psFlux_<band>` that points to the native quantity `<band>_base_PsfFlux_instFlux` (and similarly for flux error and flag). Should we have a corresponding set of GCR quantities for the cModel flux? 

Thanks to @erykoff for noticing this.

**Comment by erykoff** [comment]
If there's a quantity that we want the magnitudes for, we definitely want the fluxes as well.  One could argue that we only need the fluxes since you can always compute magnitudes from fluxes but not vice versa.

**Comment by wmwv** [comment]
1. Yes.  The flux equivalents of cModel should be available.  The fact that they're not in the trim and Parquet files is due to an oversight on my part.  Details below.

2. Yes, the flux equivalents of magnitudes should always be available.  In fact, DPDD only specifies things in flux (nJy).  We provide magnitudes for convenience.

# Details
There was a request for cModel magnitudes.  So I added the logic to `DC2ObjectCatalog` to generate the translation.

But the key elision that led to this current absence was that specifying a column to be made available in `generate_modifiers` in the `DC2ObjectCatalog` became the same thing as specifying what we provided in the "DPDD"-ish versions.  That wasn't consciously intentional on my part.  I wrote the `generate_modifiers` lines to provide the cModel magnitudes as they were previously only available as flux.  The point-source fluxes and magnitudes are all renamed in `generate_modifiers` to match the DPDD so those columns got listed in the minimal (`trim`) schema.

But then when we started providing the `trim` catalogs by default for performance, those were generating by taking the list of "non-native" quantities as the restrictive list of columns to include.

The DPDD currently lists several different extend-source photometry types:
Kron, Petrosian, Bulge+Disk decomposition model

cModel is not specifically one of them.

So formally the fact that cModel is available at all in the "DPDD"ish catalog is the error.  But practically we should include it as the flux and magnitude versions.

**Comment by wmwv** [comment]
I will spell the column as `cModelFlux*` here.  This will be in the same units as `psFlux`, which is presently with reference to a zeropoint of 27 mag AB (i.e. a mag 27 AB object produces is a `psFlux` of 1).

When I shift to nJy for psFlux I also shift cModelFlux to nJy.
https://github.com/LSSTDESC/gcr-catalogs/issues/243
https://github.com/LSSTDESC/DC2-production/issues/43

**Comment by yymao** [comment]
Closed by #263
