### ISSUE TITLE
galaxy_id incorrect for supernova in variable summary catalog

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/gcr-catalogs#272]
The `galaxy_id` value in `dc2_truth_run1.2_variable_summary` is supposed to be a foriegn key for `dc2_truth_run1.2_static` stored as `object_id`. However, the `galaxy_id` and `object_id`  values don't seem to match between both catalogues for supernova. For example:

```python
obj_ids = truth_static_gc.get_quantities(['object_id'])['object_id']
gal_id = truth_variable_summary_gc.get_quantities(
    ['galaxy_id'], native_filters=['sn == 1', 'galaxy_id != -1'])['galaxy_id']

print(max(obj_ids) < min(gal_id))
```

Talking this over with during the hack day, it seems that `object_id` is `galaxy_id` mod 1024:

```python
truth_variable_summary_gc = GCRCatalogs.load_catalog('dc2_truth_run1.2_variable_summary')
truth_static_gc = GCRCatalogs.load_catalog('dc2_truth_run1.2_static')


supernovae = truth_variable_summary_gc.get_quantities(
        ['galaxy_id', 'uniqueId', 'ra', 'dec'], 
        native_filters=['sn == 1', 'galaxy_id != -1']
    )

sn_id = supernovae['uniqueId'][0]
gal_id = supernovae['galaxy_id'][0]
print(f'sn_id: {sn_id}')
print(f'gal_id: {gal_id}')

redshift = truth_static_gc.get_quantities(
    ['redshift'], filters=[f'object_id == {gal_id % 1024}'])
print(f'redshift: {redshift['redshift'][0]}')
```

**Comment by danielsf** [comment]
This is a convention inherited from the LSST CatSim framework.  In order to guarantee that all astrophysical sources have a unique identifier, the final id assigned to each source is `local_id*1024+class_id` where `local_id` is the unique identifier in the sub-catalog (so, `galaxy_id` for galaxies) and `class_id` is some integer assigned to the class of objects (so: SNe have one value of `class_id`, AGN have a different value of `class_id`, etc.)

You should be able to back out `galaxy_id` from `object_id` by taking `galaxy_id = object_id//1024` (integer division by 1024; I think this is what you said in the issue).

We didn't spend a lot of time designing the schema for the truth catalog; it might be worth revisiting that conversation.

**Comment by rbiswas4** [comment]
@danielsf @yymao 
so `galaxy_id` is the `local_id` for galaxies while the `object_id` is the corresponding unique identifier. While having `galaxy_id` might be helpful for provenance, I would have said that 
```supernovae = truth_variable_summary_gc.get_quantities(
        ['galaxy_id', 'uniqueId', 'ra', 'dec'], 
        native_filters=['sn == 1', 'galaxy_id != -1']
    )
```
should return the unique id corresponding to the `galaxy_id` rather than the local id (which is some intermediate step that we don't care about). This would mean that the main identifier in GCR_Catalogs would be this unique id, rather than the local ids each group simulated.  Are there cons to this proposal?

**Comment by danielsf** [comment]
Sorry.  I misinterpreted the original bug report.

I believe that you will find if you additionally select on `sprinkled==0` that limiting `galaxy_id!=-1` means that you *only* get SNe that were injected by the sprinkler.  These SNe should have `galaxy_id` that do not correspond to anything in `protoDC2`, since they represent systems that were added on top of `protoDC2`.

I do not have a quick explanation for why there are no unsprinkled SNe with `galaxy_id!=-1`.

**Comment by rbiswas4** [comment]
Sorry, I am lost. Is the original bug report you are referring  to the first post ?

I think there are different things here:
- [ ] `galaxy_id` vs `object_id`
- [ ] what does `galaxy_id` = -1 mean (I thought this was no galaxy in the simulated/SAM catalog. )
- [ ] If `galaxy_id` == -1, is `object_id` == -1 ? (hostless?) 
- [ ] What does `sprinkled` mean and what values can it take? `sprinkled` = 1 means transient created by sprinkler?  Or galaxy created by sprinkler ? What about the galaxy that was taken out ? What about the SN that are sprinkled  without the `sprinkler` or are they all essentially `sprinkled`?

**Comment by danielsf** [comment]
Yes.  I am referring to Daniel's original post as "the original bug report".

To address your issues:

1) I do not think there is anything wrong with how we are handling `galaxy_id` vs. `object_id`.  Everything is self consistent, except...

2) `galaxy_id==-1` should mean that the SNe is hostless.  Unfortunately, in run 1.2, the hosted SNe catalogs did not contain a `galaxy_id` column, so *all* SNe from run 1.2 are marked with `galaxy_id==-1`.

3) `sprinkled` can be either 0 or 1.  `sprinkled==1` means the object was created by the sprinkler.  0 means it was not.

I don't think there is a good way to deal with (2).  We should probably re-generate the truth catalog with a `redshift` column included.  Yao thinks we should regenerate the truth catalog, anyways, since we are currently storing them as sqlite databases and those are not handling concurrency very well.

I'll issue a new light curve reference catalog as a part of my work on

https://github.com/LSSTDESC/DC2-production/issues/328

**Comment by rbiswas4** [comment]
Thanks for the explanation! 

> I do not think there is anything wrong with how we are handling galaxy_id vs. object_id

Ok. So I understand that Daniel's result is because of the lack of `galaxy_id` in the truth catalog. But if there were those ids: Are you also saying that there would be a way of accessing consistent ids for galaxies without having to deal with bitshitfs or are you saying that it is necessary due to other reasons to keep that convention?

**Comment by danielsf** [comment]
`galaxy_id` *should* be the ID of the source without any bitshifts applied.  It should map directly to the `galaxy_id` column in protoDC2.  Unfortunately, the supernovae had no `galaxy_id` column.

**Comment by rbiswas4** [comment]
Perfect ! As in there is a bug in the catalog (I would guess that is due to me), but we all agree on how the catalog reader should work, and it is already doing those things.  @djperrefort do you think this issue should be closed now?

**Comment by danielsf** [comment]
This PR

https://github.com/LSSTDESC/gcr-catalogs/pull/276

will add redshift to the variable summary truth catalog.  That will obviate the need to cross-reference against the extra-galactic catalog.

I think we are beyond assigning responsibility for anything in DC2.  DC2 simply *is*.

**Comment by djperrefort** [comment]
Having the redshifts added to the variable summary truth catalog would be a great and helpful addition. Thank you for adding it @danielsf. Considering the clarifications above, I think we can consider this issue addressed.

**Comment by danielsf** [comment]
@djperrefort That pull request has been merged.  If you use `master` of `gcr-catalogs`, you should be able to get the `redshift` of SNe directly from the `dc2_truth_run1.2_variable_summary` catalog.

To use `master`, clone the `gcr-catalogs` repo and run
```
export PYTHONPATH=/path/to/gcr-catalogs/clone/:$PYTHONPATH
```
