### ISSUE TITLE
reference catalogs will require lensed magnitudes

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/gcr-catalogs#93]
In order to accurately simulate the reference catalogs that DM will be using, we need to provide the post-lensing magnitudes of the galaxies in the extragalactic catalog, since these are the magnitudes that will actually be measured by other surveys.  Currently, protoDC2 only contains the unlensed magnitudes.

**Comment by aphearin** [comment]
@danielsf - thanks for calling this to our attention. The lensed magnitudes can be computed from the unlensed magnitudes together with the lensing magnification, which @patricialarsen has computed and included as a column in the extragalactic catalogs. So it turns out this information is derivable based on the provided information, although you are correct that there is no column where it is computed. 

@dkorytov - Please be sure to include the lensing magnification in the v3 release. @patricialarsen has pointed out that the fill value for magnification is zero when it should be unity, so please mask any zeros and replace with unity. 

CC @katrinheitmann

**Comment by yymao** [comment]
Ah, so can we add the lensed magnitudes as derived quantities into the existing protoDC2 reader, right?

**Comment by yymao** [comment]
@danielsf just want to check in with you to see if this needs to be fixed for Run 1.2 or it is only relevant in post-processing?
